- packages/keyring-snap/package.json
- yarn.lock
This will be required later on to avoid resolutions conflicts like this one:
```console
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0078: │ Invalid resolution @metamask/keyring-api@npm:^8.0.2 → npm:8.1.0
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 109ms
```
This error can be triggered when referencing some local (workspace) packages + using `yarn --check-resolutions`.
> chore(keyring-snap): update @metamask/keyring-api to ^8.1.0

- .github/workflows/build-lint-test.yml
The CI complained about entries that could not be removed from the cache even though they are no longer required, see:
- https://github.com/MetaMask/accounts/actions/runs/10900174593/job/30247230364
We do remove the `--immutable-cache` here, but we do keep the `--immutable` to avoid having any unintended modification to our lockfile.
> fix(ci): remove --immutable-cache when installing packages

- README.md
- docs/how-to-release.md
Add a small documentation file to explain how to release accounts' packages.
> docs: add documentation for releases

- release.config.json
This configuration was missing.
There is 2 strategies that can be handled by `MetaMask/action-publish-release` action:
- `fixed`: Meaning all packages sharing the same version than the "global" version get released together
* This was the strategy being used for:
- https://github.com/MetaMask/accounts/commit/e3522a2f8680e689fc70ce1d5534f4f68fa4c027
- https://github.com/MetaMask/accounts/actions/runs/10905969009/job/30266281001
- `independent`: Meaning each packages got published with their own versions in a "independent" way
* This is the strategy that we need for this monorepo
> fix(ci): fix release missing configuration

- package.json
- packages/keyring-api/CHANGELOG.md
- packages/keyring-api/package.json
- packages/keyring-eth-hd/CHANGELOG.md
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/CHANGELOG.md
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/CHANGELOG.md
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/CHANGELOG.md
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
This is the release candidate for version . See the changelogs for more details.
There was 2 attempts to create this release already:
1. https://github.com/MetaMask/accounts/pull/31
- There was a missing configuration file for one of the action which has been fixed by:
* https://github.com/MetaMask/accounts/pull/36
2. https://github.com/MetaMask/accounts/pull/37
- This was an empty PR with the right title (which is a requirement for the release workflow)
- However, one of the action to detect if this PR was a release did not go through, since the `package.json` was already set to `1.0.0`, see:
* https://github.com/MetaMask/accounts/actions/runs/10907728925/job/30272211482
The 2 previous PRs have been removed from the history to avoid having multiple `release: 1.0.0` commits.
> release:  1.0.0

- package.json
- packages/keyring-api/CHANGELOG.md
- packages/keyring-api/package.json
- packages/keyring-eth-hd/CHANGELOG.md
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/CHANGELOG.md
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/CHANGELOG.md
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/CHANGELOG.md
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
This is the release candidate for version . See the changelogs for more details.
1. This was the 3rd attempt for this release, it did not work because the commit name was wrong (`release:  1.0.0` instead of `release: 1.0.0`). We might wanna relax this "strict" check in the future, or maybe have more CI tooling to verify PRs title (at least for releases).
- https://github.com/MetaMask/accounts/pull/38
- https://github.com/MetaMask/accounts/actions/runs/10919514167/job/30307460716
The previous PR has been removed from the history to avoid having multiple `release: 1.0.0` commits.
> release: 1.0.0

- .github/dependabot.yml
Match the versioning strategy used by other MetaMask repos.
> ci: change dependabot strategy to 'increase'

- .github/dependabot.yml
- .github/workflows/build-lint-test.yml
- .github/workflows/main.yml
- .github/workflows/publish-preview.yml
- .github/workflows/publish-release.yml
- packages/keyring-snap-bridge/package.json
- yarn.lock
The current Dependabot configuration is not working. This change copies the configuration from [MetaMask/core](https://github.com/MetaMask/core) to attempt to fix the issue.
It also updates some actions and adds the `--immutable-cache` flag to some `yarn install` invocations.
The `@metamask/keyring-api` dependency used by `@metamask/eth-snap-keyring` is moved to `peerDependencies` and bumped to 8.1.1.
> ci: update actions, dependabot config, and internal dependencies

- packages/keyring-api/package.json
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/package.json
Some dependencies have been wrongly set as `dependencies`, so moving them back to `devDependencies`.
> chore: move some `dependencies` to `devDependencies`

- docs/how-to-release.md
- package.json
- scripts/release.sh
Adding a small script to help doing release "automatically".
If `gh` is available, then the PR will be created automatically. If not available, then the script will output an URL that can be used to create the PR (with the right title and body).
> feat: add scripts/release.sh + update release docs

- package.json
- packages/keyring-api/CHANGELOG.md
- packages/keyring-api/package.json
- packages/keyring-eth-hd/CHANGELOG.md
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/CHANGELOG.md
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/CHANGELOG.md
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/CHANGELOG.md
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
This is the release candidate for version 2.0.0. See the changelogs for more details.
> release: 2.0.0

- .syncpackrc
- packages/keyring-snap-bridge/package.json
- yarn.lock
Use `workspace:^` for internal use of `@metamask/keyring-api`.
> chore(deps): use workspace version of `keyring-api`

- .syncpackrc
This PR updates the `syncpack`'s configuration to use the `workspace:^` version of the `keyring-api` everywhere<sup>(1)</sup>, not only on `dev` and `peer` dependencies. See `syncpack`'s [documentation](https://jamiemason.github.io/syncpack/config/version-groups/banned/#dependencytypes) for more information.
1: except in the `version` element of the `keyring-api` `package.json` file.
> chore: use workspace version of 'keyring-api'

- package.json
- packages/keyring-api/CHANGELOG.md
- packages/keyring-api/package.json
- packages/keyring-eth-hd/CHANGELOG.md
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/CHANGELOG.md
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/CHANGELOG.md
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/CHANGELOG.md
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
This is the release candidate for version 3.0.0. See the changelogs for more details.
> release: 3.0.0

- .syncpackrc
- package.json
- packages/keyring-api/package.json
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.test.ts
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/package.json
- yarn.lock
This PR solves the warnings about peer dependencies not being correctly met:
```
➤ YN0060: │ eslint-plugin-import is listed by your project with version 2.27.5 (p45f26), which doesn't satisfy what @metamask/eslint-config requests (~2.26.0).
➤ YN0002: │ @metamask/eth-ledger-bridge-keyring@workspace:packages/keyring-eth-ledger-bridge doesn't provide @lavamoat/preinstall-always-fail (p531bc), requested by @lavamoat/allow-scripts.
➤ YN0002: │ @metamask/eth-simple-keyring@workspace:packages/keyring-eth-simple doesn't provide @lavamoat/preinstall-always-fail (p62368), requested by @lavamoat/allow-scripts.
➤ YN0002: │ @metamask/eth-snap-keyring@workspace:packages/keyring-snap-bridge doesn't provide @lavamoat/preinstall-always-fail (pb95fd), requested by @lavamoat/allow-scripts.
➤ YN0002: │ …
```
> chore: fix post-install validation warnings

- packages/keyring-api/package.json
- packages/keyring-snap-bridge/package.json
- yarn.lock
Bump the following dependencies:
- `@metamask/snaps-sdk` (6.5.1 to 6.6.0)
- `@metamask/snaps-controllers` (9.7.0 to 9.9.0)
- `@metamask/utils` (7.8.1 to 8.2.0)
> chore(deps): bump '@metamask/*' dependencies

- .github/workflows/close-stale-issues.yml
Adds a workflow to check for stale PRs and issues. After 60 days of inactivity, the issue or PR will be marked as stale and will be closed 14 days later if there is no follow-up.
> ci: add workflow to close stale issues and pull requests

- packages/keyring-eth-ledger-bridge/jest.config.js
- packages/keyring-eth-ledger-bridge/src/ledger-keyring.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-keyring.ts
The `addAccounts` method should return newly create accounts, instead of all the accounts present in the keyring.
Related: https://github.com/MetaMask/accounts-planning/issues/615
> fix!(keyring-eth-ledger-bridge): change `addAccounts` to return new accounts only

- .github/workflows/publish-preview.yml
Preview builds change the cache to use a different package name of the local dependencies, so the build needs to be able to change the local cache that is build during the preparation phase.
> ci: allow mutable cache for preview builds

- .vscode/settings.json
- packages/keyring-api/docs/btc-methods.md
- packages/keyring-api/src/btc/types.ts
**BREAKING:** This PR renames the Bitcoin `btc_sendmany` method to `sendBitcoin`.
This change aims to differentiate the existing method from the `sendmany` method defined by the Bitcoin Core RPC API. It also removes unused parameters.
Issue: https://github.com/MetaMask/accounts-planning/issues/641
> feat!: rename `btc_sendmany` to `sendBitcoin`

- jest.config.packages.js
- package.json
- packages/keyring-api/package.json
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/jest.config.js
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/jest.config.js
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/jest.config.js
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/package.json
Cleaning up jest config files + thresholds.
Also the coverage will now be enabled by default when running `yarn test`.
> chore: update jest config + include coverage for `yarn test` command

- packages/keyring-api/package.json
- yarn.lock
Bump `@metamask/providers` requirement to:
- use `@metamask/rpc-errors` min 7.0.0 for consistent error handling
- not have type error from `@metamask/providers` reference to readable-stream
> chore(keyring-api): update peer dependency `@metamask/providers@^17.2.0` -> `^18.1.0`

- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/package.json
- packages/keyring-snap-bridge/package.json
- yarn.lock
Bump `@metamask/eth-sig-util` to latest.
- https://github.com/MetaMask/eth-sig-util/blob/main/CHANGELOG.md
> chore: bump dependency `eth-sig-util@^7.0.3` -> `^8.0.0`

- yarn.lock
This PR bumps `secp256k1` to 4.0.4 to solve a security advisory.
> chore(deps): bump `secp256k1` to 4.0.4

- packages/keyring-api/src/api/account.ts
- packages/keyring-api/src/eth/utils.test.ts
- packages/keyring-api/src/index.ts
- packages/keyring-api/src/internal/types.ts
- packages/keyring-api/src/sol/index.ts
- packages/keyring-api/src/sol/types.test-d.ts
- packages/keyring-api/src/sol/types.test.ts
- packages/keyring-api/src/sol/types.ts
We are adding the `SolAccountType` to support Solana account creation.
> feat: adds Solana account type to keyring API

- packages/keyring-api/src/index.ts
- packages/keyring-snap-bridge/src/KeyringSnapControllerClient.ts
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
The `JsonRpcRequest` type was used in the bridge but not "officially" exported by the `keyring-api` (hence the import from the `dist` folder).
To avoid this pattern, we now export it properly.
> fix: export `JsonRpcRequest` + remove imports from `dist` folder

- packages/keyring-eth-hd/src/index.js
- packages/keyring-eth-hd/test/index.js
This PR refactors the `eth-hd-keyring` constructor to remove the deserialization step directly in the constructor. This lets us turn `deserialize` into a proper async function and use an async version of `mnemonicToSeed` (which should be swapped out for something faster in the future). 
This is a breaking change and requires that all usage of `eth-hd-keyring` calls `deserialize` with the arguments previously passed into the constructor. This seems to already be the case in the `KeyringController`, but may deserve a more thorough look.
This PR also changes the function signature of `generateRandomMnemonic`, making this an async function as well.
Appreciate any feedback and/or sanity checks on this!
> refactor(keyring-eth-hd)!: move seed generation to deserialization

- packages/keyring-eth-hd/package.json
- packages/keyring-eth-hd/src/index.js
- packages/keyring-eth-hd/test/index.js
- yarn.lock
Uses the latest version of `@metamask/keytree`, which allows passing `cryptographicFunctions` for derivation of the mnemonic seed. Also reintroduces constructor arguments to allow passing of `cryptographicFunctions` to `HdKeyring`.
Follow-up PR to https://github.com/MetaMask/accounts/pull/100
> feat(keyring-eth-hd): allow passing native implementations of cryptography

- package.json
- packages/keyring-eth-hd/CHANGELOG.md
- packages/keyring-eth-hd/package.json
This reverts commit 1777a35495b4f0f41de66d60a518f589a4e03e19.
---
The release was not published cause the `eth-hd-keyring` was not built by `ts-bridge` properly. See:
- https://github.com/MetaMask/accounts/pull/104
> Revert "release: 13.0.0 (#103)"

- packages/keyring-eth-ledger-bridge/jest.config.js
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-ledger-bridge/src/ledger-bridge.ts
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.ts
- packages/keyring-eth-ledger-bridge/src/ledger-keyring.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-keyring.ts
- packages/keyring-eth-ledger-bridge/src/ledger-mobile-bridge.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-mobile-bridge.ts
- yarn.lock
The original feature requirement is listed here:
- https://github.com/MetaMask/accounts-planning/issues/544
This PR will enable clear signing feature in `signTransaction` and `signEIP712` typed data in `@metamask/eth-ledger-keyring-bridge` library. please refer to ledger official document for detail: https://developers.ledger.com/docs/clear-signing/getting-started
This PR has done following changes:
1. change the `deviceSignTypedData` and `deviceSignTransaction` method to use new API suggested by ledger team which support clear signing.
2. change `ledger-keyring.ts` to adapt new API format for `deviceSignTypedData`.
3. fix all unit tests issue.
> feat(keyring-eth-ledger-bridge)!: enable ledger clear signing

- package.json
- packages/keyring-eth-ledger-bridge/CHANGELOG.md
- packages/keyring-eth-ledger-bridge/package.json
This reverts commit 2c86434f6ef4e4b700540e6aa6d3a52ba17d5321.
---
This release could not get through because our new packages (resulting from the split of the `keyring-api`) are not yet published on `npm` and the release scripts uses them during the release process.
To remove them from the list of packages, we should use a version of `0.0.0`, see:
- https://github.com/MetaMask/action-publish-release/blob/main/scripts/get-release-packages.sh#L43
> Revert "release: 15.0.0 (#123)"

- packages/keyring-internal-api/package.json
- packages/keyring-snap-client/package.json
- packages/keyring-snap-internal-client/package.json
- packages/keyring-snap-sdk/package.json
- packages/keyring-utils/package.json
Those packages are not released/published yet. To avoid considering those packages during the release process, we have to use the `0.0.0` version, see:
- #123
> fix: fix version for new packages `0.0.1` -> `0.0.0`

- package.json
- packages/keyring-api/package.json
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/package.json
- packages/keyring-internal-api/package.json
- packages/keyring-snap-bridge/package.json
- packages/keyring-snap-client/package.json
- packages/keyring-snap-internal-client/package.json
- packages/keyring-snap-sdk/package.json
- packages/keyring-utils/package.json
- yarn.lock
This new version fixes a bug with CJS reexports.
See this [changelog](https://github.com/ts-bridge/ts-bridge/blob/main/packages/cli/CHANGELOG.md#061) for more details.
> build: use `ts-bridge/cli@0.6.1`

- packages/keyring-api/tsconfig.json
- packages/keyring-snap-bridge/tsconfig.json
- packages/keyring-snap-client/tsconfig.json
- packages/keyring-snap-internal-client/tsconfig.json
- packages/keyring-snap-sdk/tsconfig.json
Some `tsconfig.json` are not aligned with their `tsconfig.build.json`. This might cause some dev tools (that rely on `tsconfig.json` only) to not work as expected.
> fix: missing references in some tsconfig.json

- packages/keyring-api/package.json
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/package.json
- packages/keyring-internal-api/package.json
- packages/keyring-internal-snap-client/package.json
- packages/keyring-snap-bridge/package.json
- packages/keyring-snap-client/package.json
- packages/keyring-snap-sdk/package.json
- packages/keyring-utils/package.json
- yarn.lock
This contains the following bumps:
- `@metamask/utils` from `^9.3.0` to `^11.0.1`.
- `@metamask/eth-sig-util` from `^8.0.0` to `^8.1.2`.
- `@metamask/key-tree` from `^10.0.0` to `^10.0.2`.
- `@metamask/providers` from `^18.1.0` to `^18.3.1`.
With the aim of bumping `utils` to `^11.0.1` in all packages. There are some circular dependencies between accounts, core, Snaps, so this doesn't remove old versions of utils completely yet.
> Bump MetaMask dependencies

- packages/keyring-internal-api/CHANGELOG.md
- packages/keyring-internal-api/package.json
- packages/keyring-internal-snap-client/CHANGELOG.md
- packages/keyring-internal-snap-client/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
- packages/keyring-snap-client/CHANGELOG.md
- packages/keyring-snap-client/package.json
- packages/keyring-snap-sdk/CHANGELOG.md
- packages/keyring-snap-sdk/package.json
This reverts commit 680cc4b148118e061a00199386308f1dd526e6a4.
- - -
This release could not get through because I forgot to update the [top-level package.json version](https://github.com/MetaMask/accounts/blob/680cc4b148118e061a00199386308f1dd526e6a4/package.json#L3).
> Revert "release: 18.0.0 (#135)"

- package.json
- packages/keyring-internal-api/CHANGELOG.md
- packages/keyring-internal-api/package.json
- packages/keyring-internal-snap-client/CHANGELOG.md
- packages/keyring-internal-snap-client/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
- packages/keyring-snap-client/CHANGELOG.md
- packages/keyring-snap-client/package.json
- packages/keyring-snap-sdk/CHANGELOG.md
- packages/keyring-snap-sdk/package.json
This is the release candidate for version 18.0.0. See the CHANGELOGs for more details.
There was a previous attempt for this release that didn't get through because of the top-level package bump that was missing, see:
- #136
- #135
> [!WARNING]
> The previous version [17.0.0](https://github.com/MetaMask/accounts/releases/tag/v17.0.0) did not report some breaking changes properly. This new version is just meant to re-align the CHANGELOGs and to fix the versioning.
> release: 18.0.0

- packages/keyring-eth-ledger-bridge/src/ledger-bridge.ts
Webpack build failed in MM extension complaining `EIP712Message` not found.
This PR will fix the issue.
> fix(keyring-eth-ledger-bridge): fix webpack build about non-exported `EIP712Message` type

- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
- packages/keyring-snap-bridge/src/account.ts
- packages/keyring-snap-bridge/src/events.ts
- packages/keyring-snap-bridge/src/migrations/index.ts
- packages/keyring-snap-bridge/src/migrations/v1.ts
- packages/keyring-utils/package.json
- packages/keyring-utils/src/btc/address.test.ts
- packages/keyring-utils/src/btc/address.ts
- packages/keyring-utils/src/btc/index.ts
- packages/keyring-utils/src/index.ts
- yarn.lock
With the new additions of the `scopes` field on the `KeyringAccount`, the Snap keyring state might be incompatible when we first deserialize it (and until it's being updated).
We initially wanted to run those migrations on the client side (extension) to update the `AccountsController` internal state, but the Snap keyring state will still be outdated. Also, the `AccountsController` is re-creating its internal state based on the accounts coming from each keyrings (including Snap accounts), so the Snap keyring state HAS TO BE updated, since it's the "source of truth" here.
> feat(keyring-snap-bridge): add Snap keyring migrations

- packages/keyring-api/src/api/caip.ts
- packages/keyring-snap-client/src/KeyringClient.test.ts
- packages/keyring-utils/src/superstruct.ts
Now those types have been moved to `@metamask/utils`, so just re-export them to keep them in the API.
Also, we are still re-defining the structs, since our `definePattern` allow for better error messages.
This is **BREAKING** for the `keyring-api` since the CAIP types used in the public API will now be more restrictive (`${string}:${string}/${string}:${string}` for `CaipAssetType` rather than a simple `string`)
> refactor!: use better CAIP types + add generic type in `definePattern`

- packages/keyring-api/src/api/caip.ts
- packages/keyring-api/src/api/keyring.ts
- packages/keyring-api/src/rpc.ts
- packages/keyring-snap-client/src/KeyringClient.test.ts
- packages/keyring-snap-client/src/KeyringClient.ts
- packages/keyring-snap-sdk/src/rpc-handler.test.ts
- packages/keyring-snap-sdk/src/rpc-handler.ts
This new method allows a Snap account to list all the owned assets for a given accounts.
It can be used in combinations with `getAccountBalances`.
The client would first fetch the assets for an account and then get the associated balances:
```ts
// Keyring client to interact with the account Snap.
const client = new KeyringClient(...);
// The account we want to retrieve assets from.
const id = '418b6f26-40e7-4b50-a768-018c9aba496d';
// Assets.
const tokens: CaipAssetType[] = [];
const nfts: CaipAssetId[] = [];
// Fetch assets:
for (const asset in await client.listAccountAssets()) {
if (isCaipAssetId(asset)) {
nfts.push(asset);
} else if (isCaipAssetType(asset)) {
tokens.push(asset);
} else {
console.warn(`Malformed asset, skipping: ${asset}`);
}
}
// Fetch token balances:
const balances = …
```
> feat: add `listAccountAssets` method

- packages/keyring-eth-ledger-bridge/package.json
- yarn.lock
Upgrade `@ledgerhq/hw-app-eth` to `6.42.0`. This will fix Ledger's handling of EIP-712 content.
> fix(keyring-eth-ledger-bridge): bump `@ledgerhq/hw-app-eth` to `^6.42.0` to fix Ledger's handling of EIP-712

- packages/keyring-api/src/api/account.ts
- packages/keyring-api/src/btc/types.test.ts
- packages/keyring-api/src/btc/types.ts
- packages/keyring-api/src/eth/constants.ts
- packages/keyring-api/src/eth/types.ts
- packages/keyring-api/src/sol/types.ts
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
- packages/keyring-snap-bridge/src/account.test.ts
- packages/keyring-snap-bridge/src/account.ts
- packages/keyring-snap-bridge/src/migrations/v1.ts
Adding a more restricted `scopes` field to each account type definitions (`Struct`).
> fix!: make `scopes` more restrictive

- packages/keyring-api/src/btc/constants.ts
- packages/keyring-api/src/btc/types.test.ts
- packages/keyring-api/src/eth/constants.ts
- packages/keyring-api/src/eth/types.ts
- packages/keyring-api/src/events.test.ts
- packages/keyring-api/src/sol/constants.ts
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/migrations/v1.ts
Rename all `*Scopes` enums to `*Scope` to match the pattern used for other enums.
> refactor!: rename `*Scopes` enums to `*Scope`

- packages/keyring-api/src/eth/types.ts
- packages/keyring-api/src/sol/types.ts
- packages/keyring-utils/src/superstruct.ts
- packages/keyring-utils/src/types.ts
Now that `definePattern` has been moved to `@metamask/utils` we can our local one.
> refactor: use `definePattern` from `@metamask/utils`

- packages/keyring-api/jest.config.js
- packages/keyring-api/src/api/account.ts
- packages/keyring-api/src/api/caip.ts
- packages/keyring-api/src/api/index.ts
- packages/keyring-api/src/api/keyring.ts
- packages/keyring-api/src/api/transaction.ts
- packages/keyring-api/src/btc/constants.ts
- packages/keyring-api/src/btc/types.ts
- packages/keyring-api/src/eth/constants.ts
- packages/keyring-api/src/eth/types.ts
- packages/keyring-api/src/rpc.ts
- packages/keyring-api/src/sol/constants.ts
- packages/keyring-api/src/sol/types.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
- packages/keyring-snap-bridge/src/logger.ts
- packages/keyring-snap-bridge/src/migrations/v1.ts
- packages/keyring-snap-client/src/KeyringClient.test.ts
- packages/keyring-snap-client/src/KeyringClient.ts
Re-exporting `Caip*` types and structs for convenience and to avoid making the consumers depending on `@metamask/utils`.
The rational being that the `@metamask/keyring-*` packages could be used in a standalone way without relying on other internal libraries that are not closely related to Snaps.
> feat: re-export `Caip*` types/structs

- .syncpackrc
This PR updates the syncpack configuration to enforce that:
- The following versions are in sync:
- `yarn` (`packageManager`)
- `node` (`engines`)
- All other dependences (`dependencies`, `peerDependencies`, ...)
- We use the `workspace:^` version of:
- `@metamask/keyring-**` packages
- `@metamask/eth-**-keyring` packages
> chore(build): update syncpack config

- packages/keyring-api/CHANGELOG.md
- packages/keyring-api/src/api/address.test.ts
- packages/keyring-api/src/api/address.ts
- packages/keyring-api/src/api/caip.ts
- packages/keyring-api/src/rpc.ts
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-client/src/KeyringClient.test.ts
We forgot to mention this in SIP-26, but the `address` being returned by `resolveAccountAddress` must use CAIP-10 format.
This is already being checked by the consumers of this method, but it's better that we catch any errors related to this at API level.
> fix(keyring-api)!: use CaipAccountId for ResolveAccountAddress.address

- package.json
- packages/keyring-api/CHANGELOG.md
- packages/keyring-api/package.json
- packages/keyring-eth-hd/CHANGELOG.md
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/CHANGELOG.md
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/CHANGELOG.md
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/CHANGELOG.md
- packages/keyring-eth-trezor/package.json
- packages/keyring-internal-api/CHANGELOG.md
- packages/keyring-internal-api/package.json
- packages/keyring-internal-snap-client/CHANGELOG.md
- packages/keyring-internal-snap-client/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
- packages/keyring-snap-client/CHANGELOG.md
- packages/keyring-snap-client/package.json
- packages/keyring-snap-sdk/CHANGELOG.md
- packages/keyring-snap-sdk/package.json
This is the release candidate for version 26.0.0. See the CHANGELOGs for more details.
> release: 26.0.0

- .github/workflows/validate-pr-title.yml
Enforces that the titles of PRs follow the conventional commit pattern.
> ci: enforce conventional commit in PR titles

- packages/keyring-eth-trezor/jest.config.js
- packages/keyring-eth-trezor/src/index.ts
- packages/keyring-eth-trezor/src/onekey-keyring.test.ts
- packages/keyring-eth-trezor/src/onekey-keyring.ts
This PR adds support for a dedicated OneKey keyring (until now it was sharing the same keyring instance than Trezor) so it's considered as a standalone device and could get its own tag inside account list.
There are two others PRs:
- metamask-extension: https://github.com/MetaMask/metamask-extension/pull/29999
- core (accounts and keyring controllers): https://github.com/MetaMask/core/pull/5216
Fixes: https://github.com/MetaMask/accounts-planning/issues/793
> feat: add dedicated OneKey keyring class

- packages/keyring-utils/src/keyring.ts
This PR is reapplying [these changes](https://github.com/MetaMask/utils/pull/232) to the Keyring type, which were reverted in the original repo.
Fixes: https://github.com/MetaMask/utils/issues/128
> fix: `Keyring.serialize` and `Keyring.deserialize` types

- packages/keyring-utils/CHANGELOG.md
- packages/keyring-utils/src/index.ts
With https://github.com/MetaMask/accounts/pull/201 the `Keyring` type has been added to `@metamask/keyring-utils`, specifically under `src/keyring.ts`. Though this new file is currently not exported from `index.ts`. This PR fixes that
> fix: export `keyring` from `keyring-utils`

- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
We now resume the Snap execution before persisting the account into the Snap keyring state.
This allows the Snap to have an existing account (once approved or not by the user, just like before), but this delays the actual account creation on the MetaMask clients (more specifically, the `AccountsController` in this case), which allows other controllers to react to the `AccountsController:accountCreated` event and to directly fetch account informations (assets/balances) from the Snap.
In the following example, the `SomeOtherController` cannot use the account because the account wasn't persisted by the Snap yet:
```ts
// Snap keyring methods
snap.createAccount = () => {
const account = ...;
await emitSnapKeyringEvent(AccountCreated, { account }); // -> This will trigger …
```
> feat(keyring-snap-bridge): make account creation async

- package.json
- packages/keyring-api/package.json
- packages/keyring-eth-hd/package.json
- packages/keyring-eth-ledger-bridge/package.json
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-trezor/package.json
- packages/keyring-internal-api/package.json
- packages/keyring-internal-snap-client/package.json
- packages/keyring-snap-bridge/package.json
- packages/keyring-snap-client/package.json
- packages/keyring-snap-sdk/package.json
- packages/keyring-utils/package.json
- yarn.lock
This PR fixes the type issue in `@metamask/eth-simple-keyring` where the TypedTransaction is not being exported. 
Error:
```
TypeError: Cannot destructure property 'TypedTransaction' of '_ethereumjs_tx__WEBPACK_IMPORTED_MODULE_0___default(...)' as it is undefined.
at ./node_modules/@metamask/eth-simple-keyring/dist/simple-keyring.mjs (http://localhost:6006/vendors-node_modules_metamask_keyring-controller_dist_KeyringController_mjs.iframe.bundle.js:7880:9)`
```
> build: bump `ts-bridge` to `0.6.3` (fix some un-exported types)

- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
- packages/keyring-utils/src/types.ts
Adding a new deferred promise and passing it down to `addAccount` which allows this callback to actually "await" for `saveState` to finish (since this part of the flow is asynchronous and not "awaited" anymore).
> feat(keyring-snap-bridge)!: add `onceSaved` deferred promise for `addAccount` callback

- README.md
- packages/keyring-eth-simple/CHANGELOG.md
- packages/keyring-eth-simple/package.json
- packages/keyring-eth-simple/src/simple-keyring.test.ts
- packages/keyring-eth-simple/src/simple-keyring.ts
- packages/keyring-eth-simple/tsconfig.build.json
- packages/keyring-eth-simple/tsconfig.json
- yarn.lock
- **BREAKING:** The `SimpleKeyring` class now implements `Keyring` from `@metamask/keyring-utils` ([#217](https://github.com/MetaMask/accounts/pull/217))
- The `deserialize` method now requires a `string[]` argument
> refactor!: `SimpleKeyring` uses `@metamask/keyring-utils`

- README.md
- packages/keyring-eth-trezor/CHANGELOG.md
- packages/keyring-eth-trezor/jest.config.js
- packages/keyring-eth-trezor/package.json
- packages/keyring-eth-trezor/src/trezor-keyring.test.ts
- packages/keyring-eth-trezor/src/trezor-keyring.ts
- packages/keyring-eth-trezor/tsconfig.build.json
- packages/keyring-eth-trezor/tsconfig.json
- yarn.lock
The `TrezorKeyring` is being overhauled to implement the `Keyring` type from `@metamask/utils`. Most of the changes are due to the addresses type that is now `Hex` 
```
- **BREAKING:** `TrezorKeyring` now implements the `Keyring` type ([#194](https://github.com/MetaMask/accounts/pull/194))
- The class does not extend `EventEmitter` anymore.
- The `TrezorKeyring.accounts` class variable is now a `readonly Hex[]` array.
- The `addAccounts` method signature has been changed
- An `amount` number parameter is now required to specify the number of accounts to add.
- The method now returns a promise resolving to an array of `Hex` addresses.
- The `deserialize` method now requires a `TrezorControllerOptions` object as a parameter.
- The `unlock` method now returns `Promise<Hex>`
- The …
```
> refactor!: `TrezorKeyring` implements `Keyring` type

- packages/keyring-eth-hd/test/index.test.ts
One of the test for the HD keyring is a long-running one, and it sometimes make the CI fails:
- https://github.com/MetaMask/accounts/commit/4f0115dc27245f0183517a2cf092acaa5ad5c79b
- https://github.com/MetaMask/accounts/actions/runs/13419393891/job/37488188415
To avoid flakiness, we just increase the timeout.
We could also update the test itself, but I think this makes sense to go with the timeout option for now.
> test(keyring-eth-hd): use bigger timeout for flaky test

- packages/keyring-utils/src/scopes.test.ts
- packages/keyring-utils/src/scopes.ts
Adding new util functions to compare 2 scopes (CAIP-2 chain ID) together (also supporting the special EOA case: `eip155:0`).
> feat(keyring-utils): add `isScopeEqual` + `isScopeEqualToAny`

- packages/keyring-api/src/events.test.ts
- packages/keyring-api/src/events.ts
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
Some preinstalled snaps (such as the institutional snap, and some non EVMs) may need to create accounts non-interactively. Additionally, the profile sync feature might require accounts to be restored without user input.
Users normally are asked to name their snap accounts, but this isn't appropriate where a canonical name exists.
This adds `displayAccountNameDialog` similar to `displayConfirmation`
It's intended that similar logic would be used in the client that is used for displayConfirmation ([extension code](https://github.com/MetaMask/metamask-extension/blob/2ca6b570a3580fa8b7dd18af492e8c1db702d814/app/scripts/lib/snap-keyring/snap-keyring.ts#L208)), i.e. it would default to true, and negation would only be allowed in the case of preinstalled snaps.
- Institutional snap gets names …
> feat(keyring-snap-bridge): add `displayAccountNameSuggestion` flag

- packages/keyring-internal-api/CHANGELOG.md
- packages/keyring-internal-api/package.json
- packages/keyring-internal-api/src/eth/EthKeyring.ts
- packages/keyring-internal-api/tsconfig.build.json
- packages/keyring-internal-api/tsconfig.json
- yarn.lock
The `Keyring<Json>` from `@metamask/utils` has been deprecated in favor of `Keyring` from `@metamask/keyring-utils`. This PR changes the type extended by `EthKeyring` with the new one
> refactor(keyring-internal-api)!: use `Keyring` from `keyring-utils`

- packages/keyring-utils/src/index.ts
- packages/keyring-utils/src/scopes.test.ts
> fix(keyring-utils): fix missing export for `isScope{Equal,EqualToAny}`

- packages/keyring-api/src/api/transaction.ts
We forgot to add this into the struct itself.
> fix(keyring-api): fix missing `Transaction.status` for `'swap'`

- packages/keyring-eth-trezor/package.json
- yarn.lock
Bump `@trezor/connect-web` from v9.1.11 to v9.5.0
[Trezor's changelog](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/CHANGELOG.md)
> _Starting with this release we changed de target in all @trezor packages to ES2022. It might be problematic in some very old environment or if you use Typescript with lower than ES2022 you might have to add ES2022 lib to your tsconfig. We are also include esm builds in our npm packages. For now only in @trezor/connect-plugin-stellar and @trezor/connect-plugin-ethereum._
> 
> _Another important change comes from 013f14a where we ping trezor-bridge and if it comes online connect would ditch webusb transport and start using bridge instead. This should help potential inconsistent states of device communication._
> chore: bump trezor/connect-web

- packages/keyring-snap-sdk/src/index.ts
- packages/keyring-snap-sdk/src/time.test.ts
- packages/keyring-snap-sdk/src/time.ts
Some of our methods/handlers requires a UNIX timestamp, so adding those helpers to avoid having doing manual conversions in the Snaps themselves.
> feat(keyring-snap-sdk): add UNIX timestamp helpers

- packages/keyring-eth-trezor/package.json
- yarn.lock
This reverts commit fa5d9ce8b6e12b2bd494aa30afff560e53a379cb.
- - -
Reverting this one to use the same version range as the extension until we decide to fully upgrade to the next version:
- https://github.com/MetaMask/metamask-extension/pull/30640
> revert: chore: bump trezor/connect-web (#234)

- packages/keyring-eth-hd/src/hd-keyring.test.ts
- packages/keyring-eth-hd/src/hd-keyring.ts
Store the computed mnemonic seed in the `HdKeyring` class which allows it to be re-used by other parts of MetaMask doing key derivation on compatible curves.
This will unlock some performance improvements in the Snaps platform that currently uses the mnemonic and recomputes the seed for key derivation.
> feat(keyring-eth-hd): store mnemonic seed in `HdKeyring` class

- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
The Snap keyring re-publishes some Snap events and most of those events use a mapping between an "account ID" and the event info/data.
Currently, we are not checking that those "account IDs" belongs to the Snap that fires the events. There are 2 problems with this:
1. A Snap could be using an invalid account ID (or an ID that it does not own) and send some wrong data for that account
2. There could be some race-conditions where an event is being sent by the Snap for an account that no longer exists
- This one is partially the Snap's fault, but we might want to have some guard around this logic to prevent firing those events to some other controllers (which will result in even more errors)
> fix(keyring-snap-bridge): filter invalid accounts from `SnapKeyring:account*Updated` events

- packages/keyring-api/docs/sol-methods.md
Update SOL methods:
- Replaces base64 signatures with base58, which is the standard encoding for signatures on Solana
- Improves examples with real data
- Improves descriptions
> feat: update sol methods

- packages/keyring-api/src/api/index.ts
- packages/keyring-api/src/api/keyring.ts
- packages/keyring-api/src/api/options.ts
- packages/keyring-api/src/events.test.ts
- packages/keyring-api/src/events.ts
- packages/keyring-snap-bridge/src/SnapIdMap.test.ts
- packages/keyring-snap-bridge/src/SnapIdMap.ts
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
- packages/keyring-snap-bridge/src/events.ts
- packages/keyring-snap-bridge/src/index.ts
- packages/keyring-snap-bridge/src/options.ts
Introducing a new way of handling internal options (`display*` flags) that were used to configure the account creation flow.
Initially those flags were being sent by the Snap (only interpreted for preinstalled Snaps) itself to allow to skip some specific steps of the flow (e.g display the account name input OR display the confirmation about the account creation action).
The main problem with the previous approach is that the caller (MetaMask here) of `keyring_createAccount` cannot skip those steps programmatically. It's up to the Snap to the Snap to emit the right flags with the correct values during the flow.
- - -
With the new approach, we "hide" those flags behind a context that is owned by the Snap keyring. In addition to that, we've added a new `SnapKeyring.createAccount` method that …
> feat!: add `SnapKeyring.createAccount` + internal options

- packages/keyring-snap-bridge/src/options.ts
Requires:
New flag to be able to not select the account at the end of the account creation flow.
> feat(keyring-snap-bridge): add `setSelectedAccount` internal option

- packages/keyring-eth-ledger-bridge/src/ledger-keyring.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-keyring.ts
This PR will fix the ledger sign transaction issue due to this ethereumjs upgrade PR https://github.com/MetaMask/accounts/pull/209 
and basically the ethereumjs upgrade code change make the transaction rawTxHex contain `0x` prefix which is not valid for to @ledgerhq/hw-eth-app clearSignTransaction function. that functions expect a rawTxHex without `0x` prefix.
> fix(keyring-eth-ledger-bridge): trim `0x` prefix for  `signTransaction` (due to latest `@ethereumjs` upgrade)

- .syncpackrc
- packages/keyring-eth-trezor/package.json
- yarn.lock
Similar to:
- https://github.com/MetaMask/accounts/pull/234
But just use a stricter version range to match the one from the extension, see:
- https://github.com/MetaMask/metamask-extension/pull/30640
We should remove the `syncpack` rule once we agree on moving on to the next minor (or higher) of this package. For now it has been decided to only bump the patch version to avoid introducing too many changes for Trezor support.
> chore: update `@trezor/connect-web`

- package.json
- packages/keyring-api/src/eth/types.test-d.ts
- scripts/tsd-test.sh
Simplify and fix the `tsd-test.sh` wrapper again. Also fixing the typing tests that went unnoticed with the introduciont of `scopes`.
> fix: fix `tsd-test.sh` + add top-level `test:types` rule

- packages/keyring-api/src/events.test-d.ts
- packages/keyring-api/src/events.ts
- packages/keyring-snap-sdk/src/snap-utils.ts
Currently, the `emitSnapKeyringEvent` iss using a generic payload type (like a `Record<string, Json>`). We were already using `superstruct` under the hood to check that payload, but the error was then thrown at runtime.
This new implementation allows to extract the actual payload type associated with the event to get errors at compile-time.
> feat: use event payload type for `emitSnapKeyringEvent`

- packages/keyring-eth-ledger-bridge/jest.config.js
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.ts
The Ledger iframe messaging system is being refactored to be promise based instead of using callbacks. Moreover, `#sendMessage` now throws a timeout error when the message takes to long to get replied by the iframe
Related to https://github.com/MetaMask/accounts/issues/258
> fix: ledger iframe messages timeout

- packages/keyring-eth-ledger-bridge/jest.config.js
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.ts
This PR increases the message response timeout for certain requests that require the user to interact with the device, or the timeout would be triggered too early, not giving enough time for the user to accept a signature request on its device
> fix: increase ledger timeout for user action requests

- packages/keyring-api/src/api/transaction.ts
> feat(keyring-api): add bridge types + interaction transaction type

- packages/keyring-eth-ledger-bridge/jest.config.js
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-iframe-bridge.ts
https://github.com/MetaMask/accounts/pull/271 introduced timeouts for all messages between the Ledger bridge and the iframe. Though a 20-second timeout may not be enough for the user to grab the device and accept the request - especially if the user wants to look closely at the signature request on the hardware device.
For this reason, the timeout is being removed for messages requiring user intervention, while keeping it for messages that do not expect user actions (i.e. `updateTransportMethod` and `attemptMakeApp`)
> refactor: remove timeout for messages requiring user actions

- packages/keyring-api/package.json
- packages/keyring-api/src/api/account.ts
- packages/keyring-api/src/btc/types.test-d.ts
- packages/keyring-api/src/btc/types.test.ts
- packages/keyring-api/src/btc/types.ts
- packages/keyring-api/src/eth/utils.test.ts
- packages/keyring-internal-api/src/types.ts
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/account.ts
- packages/keyring-snap-bridge/src/migrations/v1.ts
- packages/keyring-utils/src/btc/address.test.ts
- packages/keyring-utils/src/btc/address.ts
- yarn.lock
- Adds support for remaining Bitcoin account types.
- Adds stricter validation checks for the decoding of the addresses. Removes `bech32` dependency in favor of `bitcoin-address-validation`. 
- Removes size limit of scopes for Bitcoin accounts as testnet accounts span multiple scopes. `testnet`, `testnet4` and `signet` are the same account (same address).
`p2sh` is a shortcut for `p2wpkh-p2sh` (nested segwit).
* Fixes: https://consensyssoftware.atlassian.net/browse/NNT-329
> feat: bitcoin account types

- README.md
- packages/keyring-snap-sdk/package.json
- yarn.lock
This dependency is needed at runtime (to access `*Struct`s).
> fix(keyring-snap-sdk)!: make `@metamask/keyring-api` a peer dependency

- packages/keyring-eth-ledger-bridge/jest.config.js
- packages/keyring-eth-ledger-bridge/src/ledger-keyring.test.ts
- packages/keyring-eth-ledger-bridge/src/ledger-keyring.ts
Added static method to identify Ledger-specific errors and improved error handling in the LedgerKeyring class. Now, specific error messages are thrown for user-rejected transactions and when blind signing is disabled, providing clearer feedback to users during transaction signing.
> feat(keyring-eth-ledger-bridge): enhance error handling for Ledger signing operations

- package.json
- packages/keyring-eth-trezor/CHANGELOG.md
- packages/keyring-eth-trezor/package.json
- packages/keyring-utils/CHANGELOG.md
This is the release candidate for version 52.0.0. See the CHANGELOGs for more details.
> release: 52.0.0

- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/src/SnapKeyring.test.ts
- packages/keyring-snap-bridge/src/SnapKeyring.ts
This PR introduces a flag to control whether the `AnyAccountType.Account` generic account type is allowed by the `SnapKeyring`, with validation checks during account creation and updates.
**BREAKING**: The constructor now takes an options object.
> feat(keyring-snap-bridge)!: implement `AnyAccountType` handling in `SnapKeyring`

- packages/account-api/CHANGELOG.md
- packages/account-api/src/api/multichain/account.ts
- packages/account-api/src/api/multichain/wallet.ts
- packages/account-api/src/api/provider.ts
- packages/account-api/src/index.test.ts
To avoid adding an event-based mechanism to the `AccountProvider` we (for now) rely on external wallet sync's (which will be handle by the new `MultichainAccountService`.
This allow existing wallets to "find" new accounts and potentially create new missing multichan accounts.
Also, we now enforce `Bip44Account<Account>` for all `Multichain*` classes. This allows us to use `options.entropy.groupIndex` and quickly index multichain accounts based on that, thus, forcing the `AccountProvider` to only provide valid BIP-44 accounts too.
> feat(account-api): enforce `Bip44Account` for `MultichainAccount*` + add `MultichainAccount*.sync`

- packages/keyring-api/CHANGELOG.md
Fix a small typo in the changelog of release 19.1.0.
> chore(keyring-api): fix typo in changelog

- packages/account-api/CHANGELOG.md
- packages/account-api/src/api/group.ts
- packages/account-api/src/api/multichain/account.ts
- packages/account-api/src/index.test.ts
Similar to, but for groups.
- https://github.com/MetaMask/accounts/pull/328
This new "type" can be used to "tag" groups.
> feat: add `AccountGroupType` + `AccountGroup.type`

- packages/account-api/CHANGELOG.md
- packages/account-api/src/api/group.ts
- packages/account-api/src/api/wallet.ts
More utility type which allows for improved typing when using those functions.
This can help to not "generalize" the computed ID to be narrowed down to `Account{Wallet,Group}Id` only, using those new generics allows to keep the `AccountWalletType` within the computed typed.
> feat(account-api): add typing utility + better typing for `Account{Wallet,Group}Id`

- packages/account-api/CHANGELOG.md
- packages/account-api/src/api/multichain/group.ts
- packages/account-api/src/index.test.ts
We forgot to rename this function when removing the old implementation.
> refactor(account-api)!: rename `getGroupIndexFromMultichainAccountId` -> `getGroupIndexFromMultichainAccountGroupId`

- packages/account-api/CHANGELOG.md
- packages/account-api/src/api/bip44.ts
- packages/account-api/src/index.test.ts
Add small helper to assert an account is BIP-44 compatible.
> feat(account-api): add `assertIsBip44Account`

- package.json
- packages/keyring-api/CHANGELOG.md
- packages/keyring-api/package.json
- packages/keyring-internal-api/CHANGELOG.md
- packages/keyring-internal-api/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
This is the release candidate for version 65.0.0. See the CHANGELOGs for more details.
> release: 65.0.0

- packages/account-api/src/api/selector.test.ts
- packages/account-api/src/mocks/accounts.ts
- packages/keyring-api/src/btc/types.test.ts
- packages/keyring-api/src/btc/types.ts
- packages/keyring-snap-client/src/KeyringClient.test.ts
- packages/keyring-snap-sdk/src/rpc-handler.test.ts
Adds all Bitcoin methods to the account validation.
> feat: add all bitcoin methods

- packages/account-api/CHANGELOG.md
This entry was missing during the previous release.
> [!NOTE]
> I was waiting for this release too to re-align the `keyring-api` everywhere on `core`.
> chore(account-api): fixup changelog

- packages/keyring-internal-snap-client/CHANGELOG.md
- packages/keyring-internal-snap-client/package.json
- packages/keyring-snap-bridge/CHANGELOG.md
- packages/keyring-snap-bridge/package.json
- yarn.lock
Update `@metamask/base-controller` from v7 to v8. None of the breaking changes in v8 impacted this package.
This unblocks #278
> chore: update `base-controller`

- packages/account-api/CHANGELOG.md
- packages/account-api/package.json
- packages/account-api/src/api/bip44.ts
- yarn.lock
Checking the `.type` is insanely faster and still provide the same type guarantee.
> perf(account-api): faster isBip44Account function
