MetaMask/accounts

packages/keyring-snap/CHANGELOG.md
packages/keyring-snap/package.json

This is the release candidate for version 4.3.3.
Original release PR:
- https://github.com/MetaMask/eth-snap-keyring/pull/390

chore(keyring-snap): 4.3.3

---

.depcheckrc.yml
package.json
yarn.lock

This package is required to create releases from our monorepo.

feat: add @metamask/create-release-branch package

---

package.json
packages/keyring-api/CHANGELOG.md
packages/keyring-api/package.json
packages/keyring-eth-hd/CHANGELOG.md
packages/keyring-eth-hd/package.json
packages/keyring-eth-ledger-bridge/CHANGELOG.md
packages/keyring-eth-ledger-bridge/package.json
packages/keyring-eth-simple/CHANGELOG.md
packages/keyring-eth-simple/package.json
packages/keyring-eth-trezor/CHANGELOG.md
packages/keyring-eth-trezor/package.json
packages/keyring-snap-bridge/CHANGELOG.md
packages/keyring-snap-bridge/package.json

This is the release candidate for version 1.0.0. See the changelogs for more details.
This is the very first release of this new monorepo. All packages patch version have been bumped to avoid conflicting with existing and published versions.

release: 1.0.0

---

packages/keyring-api/package.json
packages/keyring-snap-bridge/package.json
yarn.lock

Update `@metamask/snaps-*` dependencies.

chore(deps): bump `@metamask/snaps-*` dependencies

---

packages/keyring-snap-bridge/src/SnapKeyring.ts
packages/keyring-snap-bridge/src/util.test.ts
packages/keyring-snap-bridge/src/util.ts

Sanitize redirect URL when using the Snap keyring bridge.

feat(snap-keyring-bridge): sanitize redirect URL

---

scripts/prepare-preview-builds.ts

It looks like our `peerDependencies` that was referencing workspaces packages were not working well with the preview builds.
To avoid this, we now identify those peer dependencies and move them as "normal "dependencies" (only for workspace packages).

fix(preview): support reference to workspace packages in `peerDependencies`

---

package.json
packages/keyring-eth-hd/CHANGELOG.md
packages/keyring-eth-hd/package.json
packages/keyring-eth-simple/CHANGELOG.md
packages/keyring-eth-simple/package.json
packages/keyring-eth-trezor/CHANGELOG.md
packages/keyring-eth-trezor/package.json
packages/keyring-snap-bridge/CHANGELOG.md

This is the release candidate for version 11.0.0. See the changelogs for more details.

release: 11.0.0

---

package.json
packages/keyring-eth-hd/CHANGELOG.md
packages/keyring-eth-hd/package.json

This is the release candidate for version 13.0.0. See the changelogs for more details.

release: 13.0.0

---

tsconfig.build.json
tsconfig.json

Adds `keyring-eth-hd` to the tsconfig, since otherwise it would not be built at release time.

build: add `keyring-eth-hd` to tsconfig

---

packages/keyring-snap-bridge/src/SnapKeyring.ts

There was a leak with the deferred promises when an asynchronous request was not allowed.

fix(keyring-snap-bridge): fix async Snap request (submitRequest) leak

---

.github/workflows/validate-labels.yml

Nit: rename the `check-labels.yml` file to `validate-labels.yml`.

ci: rename flow `check-labels` to `validate-labels`

---

packages/keyring-internal-snap-client/CHANGELOG.md
packages/keyring-snap-client/CHANGELOG.md

Some changelog entries were missing.

chore: fixup changelogs

---

package.json
packages/keyring-api/CHANGELOG.md
packages/keyring-api/package.json
packages/keyring-eth-hd/CHANGELOG.md
packages/keyring-internal-api/CHANGELOG.md
packages/keyring-internal-api/package.json
packages/keyring-internal-snap-client/CHANGELOG.md
packages/keyring-internal-snap-client/package.json
packages/keyring-snap-bridge/CHANGELOG.md
packages/keyring-snap-bridge/package.json
packages/keyring-snap-client/CHANGELOG.md
packages/keyring-snap-client/package.json
packages/keyring-snap-sdk/CHANGELOG.md
packages/keyring-snap-sdk/package.json
packages/keyring-utils/CHANGELOG.md
packages/keyring-utils/package.json

This is the release candidate for version 33.0.0. See the CHANGELOGs for more details.

release: 33.0.0

---

package.json
packages/keyring-eth-hd/CHANGELOG.md
packages/keyring-eth-hd/package.json
packages/keyring-eth-ledger-bridge/CHANGELOG.md
packages/keyring-eth-ledger-bridge/package.json
packages/keyring-eth-simple/CHANGELOG.md
packages/keyring-eth-simple/package.json
packages/keyring-eth-trezor/CHANGELOG.md
packages/keyring-eth-trezor/package.json
packages/keyring-internal-api/CHANGELOG.md
packages/keyring-internal-api/package.json

This is the release candidate for version 36.0.0. See the changelogs for more details.

release: 36.0.0

---

package.json
packages/keyring-eth-hd/CHANGELOG.md
packages/keyring-eth-hd/package.json
packages/keyring-eth-ledger-bridge/CHANGELOG.md
packages/keyring-eth-ledger-bridge/package.json
packages/keyring-eth-simple/CHANGELOG.md
packages/keyring-eth-simple/package.json
packages/keyring-eth-trezor/CHANGELOG.md
packages/keyring-eth-trezor/package.json
packages/keyring-snap-bridge/CHANGELOG.md
packages/keyring-snap-bridge/package.json
packages/keyring-utils/CHANGELOG.md
packages/keyring-utils/package.json

This is the release candidate for version 37.0.0. See the CHANGELOGs for more details.

release: 37.0.0

---

package.json
packages/keyring-snap-sdk/CHANGELOG.md
packages/keyring-snap-sdk/package.json

This is the release candidate for version 39.0.0. See the CHANGELOGs for more details.

release: 39.0.0

---

README.md
packages/keyring-eth-hd/CHANGELOG.md
packages/keyring-eth-hd/jest.config.js
packages/keyring-eth-hd/package.json
packages/keyring-eth-hd/src/hd-keyring.test.ts
packages/keyring-eth-hd/src/hd-keyring.ts
packages/keyring-eth-hd/src/index.ts
packages/keyring-eth-hd/tsconfig.build.json
packages/keyring-eth-hd/tsconfig.json
yarn.lock

The `HdKeyring` class now implements the `Keyring` type from `@metamask/keyring-utils`, getting aligned with other keyrings

refactor!: `HdKeyring` implements `Keyring` type

---

.github/CODEOWNERS

Updating CODEOWNERS file to swap `@metamask/wallet-framework-engineers` with `@metamask/core-platform`.

chore: update CODEOWNERS with `core-platform`

---

package.json
packages/account-api/CHANGELOG.md
packages/account-api/package.json
packages/keyring-api/CHANGELOG.md
packages/keyring-api/package.json
packages/keyring-internal-api/CHANGELOG.md
packages/keyring-internal-api/package.json
packages/keyring-internal-snap-client/CHANGELOG.md
packages/keyring-internal-snap-client/package.json
packages/keyring-snap-bridge/CHANGELOG.md
packages/keyring-snap-bridge/package.json
packages/keyring-snap-client/CHANGELOG.md
packages/keyring-snap-client/package.json
packages/keyring-snap-sdk/CHANGELOG.md
packages/keyring-snap-sdk/package.json
packages/keyring-utils/CHANGELOG.md
packages/keyring-utils/package.json

This is the release candidate for version 54.0.0. See the CHANGELOGs for more details.

release: 54.0.0

---

package.json
packages/account-api/CHANGELOG.md
packages/account-api/package.json

This is the release candidate for version 56.0.0. See the CHANGELOGs for more details.

release: 56.0.0

---

package.json
packages/account-api/CHANGELOG.md
packages/account-api/package.json

This is the release candidate for version 58.0.0. See the CHANGELOGs for more details.

release: 58.0.0

---

package.json
packages/account-api/CHANGELOG.md
packages/account-api/package.json

This is the release candidate for version 60.0.0. See the CHANGELOGs for more details.

release: 60.0.0

---

package.json
packages/account-api/CHANGELOG.md
packages/account-api/package.json

This is the release candidate for version 61.0.0. See the CHANGELOGs for more details.

release: 61.0.0

---

package.json
packages/account-api/CHANGELOG.md
packages/account-api/package.json

This is the release candidate for version 64.0.0. See the CHANGELOGs for more details.

release: 64.0.0

---

package.json
packages/keyring-eth-qr/CHANGELOG.md
packages/keyring-eth-qr/package.json

Releasing `@metamask/eth-qr-keyring` v1.0.0

release: 66.0.0

---

package.json
packages/account-api/CHANGELOG.md
packages/keyring-eth-qr/CHANGELOG.md
packages/keyring-eth-qr/package.json

This is the release candidate for version 69.0.0. See the changelogs for more details.

release: 69.0.0

---

package.json
packages/account-api/CHANGELOG.md
packages/account-api/package.json

This is the release candidate for version 72.0.0. See the CHANGELOGs for more details.

release: 72.0.0
